const fs = require('fs');
let code = fs.readFileSync('components/trial-experience.tsx', 'utf-8');

// The block to replace:
const oldBlock = `            <fieldset className="trial-field-half"><legend>How often? <InfoTip label="Frequency">This helps us decide whether one-off usage, credits, or a recurring subscription gives you better value.</InfoTip></legend><div className="trial-choice-grid four">{([['once','Once'],['occasionally','Sometimes'],['monthly','Monthly'],['ongoing','Ongoing']] as Array<[Frequency,string]>).map(([id,label]) => <button type="button" aria-pressed={frequency === id} onClick={() => setFrequency(id)} key={id}>{label}</button>)}</div></fieldset>

            <fieldset className="trial-field-half"><legend>{recurring ? "Monthly AI budget" : "AI budget"} <InfoTip label="AI-only budget">{recurring ? "The maximum amount you're comfortable spending each month on AI subscriptions and expected usage." : "This is your AI-only budget for this project. It can include usage credits or temporary paid access. It is not your full client or project budget."}</InfoTip></legend><div className="trial-budget-row"><select aria-label="Currency" value={currency} onChange={(event) => { const next = event.target.value as Currency; setCurrency(next); setBudgetChoice(String(suggestedBudgets(next)[2])); }}><option value="USD">USD $</option><option value="AUD">AUD A$</option><option value="VND">VND ₫</option></select>{budgets.map((amount) => <button type="button" aria-pressed={budgetChoice === String(amount)} onClick={() => setBudgetChoice(String(amount))} key={amount}>{budgetLabel(amount, currency)}</button>)}<button type="button" aria-pressed={budgetChoice === "custom"} onClick={() => setBudgetChoice("custom")}>Custom</button></div>{budgetChoice === "custom" && <label className="trial-custom-budget"><span>{currency === "VND" ? "₫" : currency === "AUD" ? "A$" : "$"}</span><input aria-label="Exact AI budget" type="number" min="0" step="any" inputMode="decimal" value={customBudget} onChange={(event) => setCustomBudget(event.target.value)} placeholder="7.50" required /></label>}</fieldset>

            {!recurring && <fieldset className="trial-field-half"><legend>Deadline <InfoTip label="Deadline">Your deadline helps us favour a workflow and tools that can realistically finish the work on time.</InfoTip></legend><input className="trial-date" type="date" min={new Date().toISOString().slice(0, 10)} value={deadline} onChange={(event) => setDeadline(event.target.value)} required /></fieldset>}`;

const newBlock = `            <fieldset className="trial-field-half"><legend>Total budget <InfoTip label="Project budget">The total you are willing to spend on one-off AI tools or usage to get this project done.</InfoTip></legend><div className="trial-budget-row"><select aria-label="Currency" value={currency} onChange={(event) => { const next = event.target.value as Currency; setCurrency(next); setBudgetChoice(String(suggestedBudgets(next)[2])); }}><option value="USD">USD $</option><option value="AUD">AUD A$</option><option value="VND">VND ₫</option></select>{budgets.map((amount) => <button type="button" aria-pressed={budgetChoice === String(amount)} onClick={() => setBudgetChoice(String(amount))} key={amount}>{budgetLabel(amount, currency)}</button>)}<button type="button" aria-pressed={budgetChoice === "custom"} onClick={() => setBudgetChoice("custom")}>Custom</button></div>{budgetChoice === "custom" && <label className="trial-custom-budget"><span>{currency === "VND" ? "₫" : currency === "AUD" ? "A$" : "$"}</span><input aria-label="Exact AI budget" type="number" min="0" step="any" inputMode="decimal" value={customBudget} onChange={(event) => setCustomBudget(event.target.value)} placeholder="20.00" required /></label>}</fieldset>

            <fieldset className="trial-field-half"><legend>Deadline <InfoTip label="Deadline">Your deadline helps us favour a workflow and tools that can realistically finish the work on time.</InfoTip></legend><input className="trial-date" type="date" min={new Date().toISOString().slice(0, 10)} value={deadline} onChange={(event) => setDeadline(event.target.value)} required /></fieldset>`;

code = code.replace(oldBlock, newBlock);
fs.writeFileSync('components/trial-experience.tsx', code);
