"use client";

import { Copy, FilePlus2, Trash2 } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { IntegrationNotice } from "./integration-notice";
import { integrationsConfigured } from "./providers";

type Strategy={_id:string;title:string;usageType:"one_off"|"monthly";budget?:number;status:string;createdAt:number;refreshAvailable?:boolean;refreshReasons?:string[]};
export function DashboardView(){const [strategies,setStrategies]=useState<Strategy[]>([]);const [error,setError]=useState("");function load(){fetch("/api/strategies").then(async response=>{const body=await response.json() as Strategy[]|{error?:string};if(!response.ok)throw new Error("error" in body?body.error:"Unable to load strategies");return body as Strategy[]}).then(setStrategies).catch(e=>setError(e instanceof Error?e.message:"Unable to load strategies"))}useEffect(()=>{if(integrationsConfigured)load()},[]);async function remove(id:string){if(!confirm("Delete this strategy?"))return;await fetch(`/api/strategies/${id}`,{method:"DELETE"});load()}async function duplicate(id:string){const response=await fetch(`/api/strategies/${id}/duplicate`,{method:"POST"});if(!response.ok){setError("Unable to duplicate strategy");return}load()}
  if(!integrationsConfigured)return <IntegrationNotice/>;return <div className="dashboard-grid"><section className="card dashboard-main"><header><h2>Recent strategies</h2><Link className="button button-primary button-small" href="/choose-usage"><FilePlus2/>Create New Strategy</Link></header>{error&&<p className="error-message">{error}</p>}{strategies.length===0?<div className="empty-state"><h2>No saved strategies yet.</h2><p>Create a strategy to see the real Convex-backed record here.</p></div>:strategies.map(strategy=><div className="strategy-row" key={strategy._id}><div><strong>{strategy.title}</strong><small>{new Date(strategy.createdAt).toLocaleDateString()} · {strategy.usageType==="one_off"?(strategy.budget===undefined?"Budget not set":`Budget $${strategy.budget} USD`):"Recurring workload"}</small>{strategy.refreshAvailable&&<span className="refresh-available" title={strategy.refreshReasons?.join("; ")}>Better plan available</span>}</div><span>{strategy.usageType==="one_off"?"One-off":"Monthly"}</span><div style={{display:"flex",gap:8}}><Link href={`/strategy/${strategy._id}/${strategy.status==="complete"?"results":"workflow"}`}>Open</Link><button style={{border:0,background:"transparent",cursor:"pointer"}} onClick={()=>duplicate(strategy._id)} aria-label="Duplicate strategy"><Copy style={{width:14}}/></button><button style={{border:0,background:"transparent",cursor:"pointer"}} onClick={()=>remove(strategy._id)} aria-label="Delete strategy"><Trash2 style={{width:14}}/></button></div></div>)}</section><aside className="card dashboard-side"><h2>Account</h2><div className="account-facts"><div><span>Identity</span><strong>Clerk</strong></div><div><span>Saved data</span><strong>Convex</strong></div><div><span>Authorization</span><strong>Session derived</strong></div><div><span>Model data</span><strong>Dated snapshots</strong></div></div></aside></div>}
