"use client";

import { Background, Controls, ReactFlow, type Edge, type Node } from "@xyflow/react";
import { ArrowDown, ArrowUp, Pencil, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { IntegrationNotice } from "./integration-notice";
import { integrationsConfigured } from "./providers";
import { apiErrorMessage } from "@/lib/client/api-error";

type StoredStep={_id:string;order:number;name:string;description:string;requirements:Record<string,unknown>;estimates:Record<string,unknown>};
type StrategyResponse={strategy:{title:string;originalInput:string;status:string};steps:StoredStep[]};
export function WorkflowEditor({strategyId}:{strategyId:string}){const router=useRouter();const [data,setData]=useState<StrategyResponse|null>(null);const [steps,setSteps]=useState<StoredStep[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const [editing,setEditing]=useState(false);
  useEffect(()=>{if(!integrationsConfigured)return;fetch(`/api/strategies/${strategyId}`).then(async response=>{const body=await response.json() as StrategyResponse|{error?:string};if(!response.ok)throw new Error("error" in body?body.error:"Unable to load workflow");return body as StrategyResponse}).then(body=>{setData(body);setSteps(body.steps.sort((a,b)=>a.order-b.order))}).catch(e=>setError(e instanceof Error?e.message:"Unable to load workflow"))},[strategyId]);
  const nodes=useMemo<Node[]>(()=>steps.map((step,index)=>({id:step._id,position:{x:index*245,y:index%2?90:20},data:{label:`${index+1}. ${step.name}`},style:{width:190,border:"1px solid #dce3ef",borderRadius:10,padding:12,fontSize:11,boxShadow:"0 8px 20px rgba(36,55,90,.06)"}})),[steps]);
  const edges=useMemo<Edge[]>(()=>steps.slice(1).map((step,index)=>({id:`e-${index}`,source:steps[index]._id,target:step._id,animated:false,style:{stroke:"#8ea6d3"}})),[steps]);
  function change(index:number,patch:Partial<StoredStep>){setSteps(current=>current.map((step,i)=>i===index?{...step,...patch}:step))}function move(index:number,dir:-1|1){const target=index+dir;if(target<0||target>=steps.length)return;const next=[...steps];[next[index],next[target]]=[next[target],next[index]];setSteps(next.map((step,i)=>({...step,order:i})))}function add(){setSteps(current=>[...current,{_id:`draft-${crypto.randomUUID()}`,order:current.length,name:"New step",description:"Describe what should happen in this step.",requirements:{requiredModalities:["text"],requiredCapabilities:[],importance:"medium",noAIEligible:false},estimates:{requests:1,inputExpected:500,outputExpected:300}}])}function remove(index:number){setSteps(current=>current.filter((_,i)=>i!==index).map((step,i)=>({...step,order:i})))}
  async function save(){const response=await fetch(`/api/strategies/${strategyId}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({steps:steps.map(({order,name,description,requirements,estimates})=>({order,name,description,requirements,estimates}))})});const body=await response.json() as {code?:string;userMessage?:string;error?:string};if(!response.ok)throw new Error(apiErrorMessage(body,"We couldn't save your workflow right now."))}
  async function approve(){setBusy(true);setError("");try{await save();const response=await fetch(`/api/strategies/${strategyId}/approve`,{method:"POST"});const body=await response.json() as {result?:unknown;code?:string;userMessage?:string;error?:string};if(!response.ok||!body.result)throw new Error(apiErrorMessage(body,"We couldn't generate recommendations right now."));sessionStorage.setItem(`benchflow:result:${strategyId}`,JSON.stringify(body.result));router.push(`/strategy/${strategyId}/results`)}catch(e){setError(e instanceof Error?e.message:"We couldn't generate recommendations right now.")}finally{setBusy(false)}}
  if(!integrationsConfigured)return <IntegrationNotice/>;if(error&&!data)return <div className="card empty-state"><h2>Workflow unavailable</h2><p>{error}</p></div>;if(!data)return <div className="card empty-state"><h2>Understanding your work…</h2><p>Loading the validated workflow from Convex.</p></div>;
  return <><div className="card" style={{height:280,marginBottom:16}}><ReactFlow nodes={nodes} edges={edges} fitView nodesDraggable={false} nodesConnectable={false} elementsSelectable={false}><Background color="#e1e7f0" gap={18}/><Controls showInteractive={false}/></ReactFlow></div><div className="workflow-list">{steps.map((step,index)=><div key={step._id} className="card workflow-step-card"><span>{index+1}</span><div><input aria-label="Step name" value={step.name} readOnly={!editing} onChange={e=>change(index,{name:e.target.value})} style={{border:0,fontWeight:650,width:"100%",outline:0}}/><textarea aria-label="Step description" value={step.description} readOnly={!editing} onChange={e=>change(index,{description:e.target.value})} style={{width:"100%",minHeight:55,border:"1px solid #e1e6ef",borderRadius:7,padding:8,marginTop:7,fontSize:10}}/><small>Importance: {String(step.requirements.importance??"medium")}</small><small>{step.requirements.noAIEligible?"Manual / No AI allowed":"AI eligible"}</small>{editing&&<label style={{display:"inline-flex",gap:5,marginTop:9,fontSize:8}}><input type="checkbox" checked={Boolean(step.requirements.noAIEligible)} onChange={e=>change(index,{requirements:{...step.requirements,noAIEligible:e.target.checked}})}/> Mark as manual or No AI</label>}</div>{editing&&<div><button onClick={()=>move(index,-1)} aria-label="Move up"><ArrowUp/></button><button onClick={()=>move(index,1)} aria-label="Move down"><ArrowDown/></button><button onClick={()=>remove(index)} aria-label="Delete step"><Trash2/></button></div>}</div>)}</div>{editing&&<button className="button button-secondary" style={{marginTop:12}} onClick={add}><Plus/> Add step</button>}{error&&<p className="error-message">{error}</p>}<div className="form-actions"><button className="button button-secondary" onClick={()=>setEditing(true)} disabled={editing||busy}><Pencil/> Edit workflow</button><button className="button button-primary" onClick={approve} disabled={busy}>{busy?"Finding your AI stack…":"Looks good — Find my AI stack"}</button></div></>}
